[format]
line-width = 120                    # same as .editorconfig
indent-width = 2                    # same as .editorconfig
indent-style = "space"              # same as .editorconfig
line-ending = "lf"                  # same as .editorconfig
persistent-line-breaks = true       # preserve existing line breaks when reformatting
default-exclude = true              # use built-in default exclusions
assignment-style = "equal"          # new option in air 0.10.0


# you can use "exclude" and "skip" to avoid formatting certain globs
