test_that("cox", {
  data("Sonar", package = "mlbench")
  task = as_task_classif(Sonar, target = "Class", positive = "M")
  splits = partition(task)
  task_train = task$clone()$filter(splits$train)
  task_test = task$clone()$filter(splits$test)
  learner <- lrn("classif.rpart", predict_type = "prob")
  learner$train(task_train)
  preds = learner$predict(task_test)
  score_cox_slope = preds$score(cox_slope$new())
  checkmate::expect_numeric(score_cox_slope)
  score_cox_intercept = preds$score(cox_intercept$new())
  checkmate::expect_numeric(score_cox_intercept)
})
